### PR TITLE
FEATURE: Use splitsh lite for faster builds

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by kdambekalns** [comment]
**DO NOT MERGE** yet, we need to wait for splitsh/lite#20 to be fixed.

**Comment by kdambekalns** [comment]
While splitsh/lite#20 is fixed by now, there are still issues with differing commit hashes, so… :/

**Comment by kitsunet** [comment]
(Somewhat) good news! I did a test split on Neos.Flow master and it lines up. Bottom 5 and top 5 commits are exactly the same, so I think we are good. Probably the moving around of folders got rid of some bad old commits.

BUT the problem is with anything pre 4.0 as TYPO3.Flow splits in 3.3 branch don't line up :(
I have no clue what has happened in one of the old commits but it seems to be bad...

**Comment by kdambekalns** [comment]
We need to find the first commit that differs, either that or the one before should cause it, no?!

**Comment by kitsunet** [comment]
it starts right in the beginning if you look closely...

The SVN foo results in TWO commits for everything via subtree split and just one via splitsh (one of the two commit hashes lines up though). BUT still every other commit lines up, so that _could_ be fine. The real problem and divergence starts with `4d563e683b436670c45eff44d1f241bda9f971ba` and the following commit. Both reverts. Those are the first commits that have different hashes between both tools. I don't know though why.

**Comment by kitsunet** [comment]
It's definitely `4d563e683b436670c45eff44d1f241bda9f971ba` (subtree) vs. `79cae3e5373fb02c1e2214c94b23732a4865742e` (splitsh). I have no idea how to analyse this further though. The graph looks better in the subtree split for me. But the actual diff makes more sense with splitsh (as it's a revert and the subtree revert reverts more than the original commit did).

Anyway two more points:
a) I think splitsh looses tags!? That's kind of a problem or did I miss something
b) If (a) is solved it could be an idea to use splitsh for branches > 3.3 as there it aligns currently. That way at some point in the future all branches are split with splitsh. If we wait there may be another unaligned commit...

**Comment by kdambekalns** [comment]
Ok, making things clickable… The commit neos/flow-development-collection@882be01390260ef055d3897ff2165eedc0222cb4 results in neos/flow@4d563e683b436670c45eff44d1f241bda9f971ba right now, using the subtree split. Splitting using splitsh it ends up in kdambekalns/flow-development-collection@79cae3e5373fb02c1e2214c94b23732a4865742e

**Comment by aertmann** [comment]
looking at it, the subtree split seems to be doing something weird right? the splitsh seems to mimic the actual commit.

**Comment by kdambekalns** [comment]
True, that's what I realised as well. But… if all our repos were "wrong" since that long ago, what did we miss? Why does it work? Or is the actual file result the same?

A bit later… we can confirm that there is no difference between the results, but the hashes differ. To maximise confusion, GitHub actually shows a difference, locally Git says it's the same (https://github.com/neos/flow/compare/3.0...kdambekalns:3.0-splitsh?expand=1 vs. `git diff 3.0..3.0-splitsh`)

**Comment by kdambekalns** [comment]
See https://github.com/splitsh/lite/issues/39 for a new issue I opened with splitsh.

**Comment by kdambekalns** [comment]
FYI: I contacted GitHub support about the "indifferent difference"… ;)

**Comment by kdambekalns** [comment]
Turns out the difference is due to a “three dot diff” vs a “two dot diff”. So, it’s normal. But it shows there is a difference in history, but the “same present”.

**Comment by kdambekalns** [comment]
The differing hashes are most likely nothing we can solve. See https://github.com/yiisoft/yii2/issues/15785#issuecomment-368860963, where it says:

---

**Why is the history different in different git versions?**

From the git subtree docs:

> Repeated splits of exactly the same history are guaranteed to be
> identical (i.e. to produce the same commit ids). Because of this, if
> you add new commits and then re-split, the new commits will be attached
> as commits on top of the history you generated last time, so 'git merge'
> and friends will work as expected.

So normally we would expect this to not happen, however a bugfix in the way commit messages are created has happend shortly after 1.8.1.1: git/git@a5b8e28 This causes the commit messages to not contain a newline at the end in the new history branch, resulting in different commit hashes.

---

Furthermore I think we have been using different git versions over time, so even the [`--git` flag](https://github.com/splitsh/lite#migrating-from-git-subtree-split) that can be given to `splitsh-lite` is not going to help us a lot.

**Comment by kdambekalns** [comment]
A full split of the Neos dev collection, including cloning the repo (but without pushes):

    php slicer.php   23.23s user 17.78s system 90% cpu 45.514 total

Seconds. Not minutes.

**Comment by kdambekalns** [comment]
Another update. In the Flow dev collection some sub-packages had the same SHA1s, most didn't. In Neos all seem to differ. Well, see above.

Anyway, here is the result of splitting `master` and `5.2.3` on Neos.Neos and Neos.Fusion.Afx (with an added `--force` on the push operation that is not yet in the slicer repo):

- https://github.com/kdambekalns/fusion-afx (splitsh-lite) vs https://github.com/neos/fusion-afx (subsplit)
- https://github.com/kdambekalns/neos (splitsh-lite) vs https://github.com/neos/neos

The _content_ seeems to match, just the _hashes_ differ.

If you agree, shall we risk running that new version? If things go horribly wrong, we can switch back to the old way - since the monorepo doesn't change, our splits can be recreated at will… or do I overlook something here?

**Comment by markusguenther** [comment]
Wow great work. Never did the splitting but when it is that much faster and just the hash is different we should give it a try :)

But I am not the expert 😃

**Comment by albe** [comment]
Okay, so from what I understand, the optimal solution would be to use `--git` for different sections of the history, depending on the git version used there (who's git version though? GH? the committers? the one used by the split job?). This is not possible AFAIS, so we're left with pushing different hashes and hoping that nothing blows up too much (I can only think of checkouts of specific hashes "breaking")?

I took a quick look on why `git subtree split` is sooooo slow, just to see if it couldn't just be fixed in the base. Well, obviously because it goes through every single commit every time. I found the reference to the `--rejoin` option (https://github.com/apenwarr/git-subtree/blob/master/git-subtree.txt#L234), which seems to work around the issue by creating a merge commit to the base repository that it can then continue from for the next `--rejoin` invokation. So in theory that would be optimal, but:
- git-subsplit, which we use right now, doesn't support that option (we'd need to fork and maintain that ourselves)
- I have no clue if the additional merge commits to the base wouldn't be super annoying
- It's not guaranteed that is similarly fast as splitsh-lite

I don't understand why there isn't just an option to provide a commit hash of the base branch to start splitting from, then how to store that would be externalized, but that's the way it is 🤷

So given all that - the effort that has already gone into this (hello sunken cost fallacy! 👋), the massive amount of time this would save now and in the future for doing releases (and saving cpu power), this looking future proof (splitsh-lite is independent of git shenanigans with the hashes over versions), the only downside seemingly being a one-time rewrite of history of the split repos, the options of going back if it's still too explosive 💥 - I would agree to try this.

**Comment by kdambekalns** [comment]
Dug into it again, I documented some findings in https://github.com/splitsh/lite/issues/65#issuecomment-1271447886.

My conclusion right now is…

- fingers crossed `splitsh/lite` is here to stay. It seems a bit unmaintained, hopefully that's because it is "feature complete" for the needs of the Symfony folks…
- we can ignore the differences, as those are only affecting the hashes, not the content – and at some point I tested how composer behaves and found the hashes have no relevance unless you pin to a commit hash (which should be really, really rare!)
- we'd need to force push for the heads (once, when switching), commits should be no problem (existing ones would be left alone)
- if things go well using our current tooling, we could switch the splitting to GH actions (see #14)

**Comment by kdambekalns** [comment]
The branches we do split daily (and for which we need to force push once):

- Neos 5.3 up to 8.2
- Flow 6.3 up to 8.2

**Pull request merged**
